// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRJfCBMnrUyM-8XteI_7CItlILcvTMna4',
    appId: '1:36188623737:web:890c1cf073161cb998d5a8',
    messagingSenderId: '36188623737',
    projectId: 'cmsc23-todo-app-jcsagun',
    authDomain: 'cmsc23-todo-app-jcsagun.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-jcsagun.appspot.com',
    measurementId: 'G-2RN9DR06K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwUiTVn5qpmRZAUpAWSIFTbGq7_P3woSs',
    appId: '1:36188623737:android:5999b989aed03afc98d5a8',
    messagingSenderId: '36188623737',
    projectId: 'cmsc23-todo-app-jcsagun',
    storageBucket: 'cmsc23-todo-app-jcsagun.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsClneXdpjxlmBt60d3vpPKMbfMvRvN4A',
    appId: '1:36188623737:ios:4a529cbe2d4f241398d5a8',
    messagingSenderId: '36188623737',
    projectId: 'cmsc23-todo-app-jcsagun',
    storageBucket: 'cmsc23-todo-app-jcsagun.appspot.com',
    iosClientId: '36188623737-42clmbpcivrrsjrfi26cu6tfscc26eda.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsClneXdpjxlmBt60d3vpPKMbfMvRvN4A',
    appId: '1:36188623737:ios:4a529cbe2d4f241398d5a8',
    messagingSenderId: '36188623737',
    projectId: 'cmsc23-todo-app-jcsagun',
    storageBucket: 'cmsc23-todo-app-jcsagun.appspot.com',
    iosClientId: '36188623737-42clmbpcivrrsjrfi26cu6tfscc26eda.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
